# Generated by Django 3.2.3 on 2021-08-11 05:47

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantNumber', models.DecimalField(decimal_places=0, max_digits=10, unique=True, verbose_name='applicantsNumber')),
                ('course', models.CharField(choices=[('BET', 'Bachelor of Engineering Technology'), ('BSE', 'Bachelor of Science in Engineering'), ('BSIE', 'Bachelor of Science in Industrial Education'), ('BTTE', 'Bachelor of Technical Teacher Education')], default='', max_length=5, verbose_name='course')),
                ('major', models.CharField(choices=[('AET', 'Automotive'), ('CT', 'Civil'), ('COET', 'Computer'), ('ESET', 'Electronics'), ('EET', 'Electrical'), ('MPET', 'Mechanical'), ('PPET', 'Powerplant'), ('ICT', 'Information Communication Technology'), ('IA', 'Industrial Arts'), ('CP', 'Computer Programming'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], default='', max_length=10, verbose_name='major')),
                ('lastName', models.CharField(max_length=50, verbose_name='lastName')),
                ('firstName', models.CharField(max_length=50, verbose_name='firstName')),
                ('middleName', models.CharField(max_length=50, verbose_name='middleName')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('contact', models.DecimalField(decimal_places=0, default='For Interview', max_digits=11, verbose_name='contact')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusOfApplicants', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('TRANSFER', 'Refer to other course')], default='For Interview', max_length=20, verbose_name='result')),
                ('applicantNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewApp.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userType', models.CharField(choices=[('head', 'Department Head'), ('admission', 'Admission'), ('faculty', 'Interviewer')], default='', max_length=10, verbose_name='userType')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='userName')),
                ('firstName', models.CharField(max_length=20, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=20, verbose_name='lastName')),
                ('is_admission', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_head', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
